/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package userInterface.Course;

import Controller.CourseController;
import Controller.SqliteController;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author 83715
 */
public class EnrollCourse extends javax.swing.JPanel {

    JPanel container;
    
    /**
     * Creates new form manageTeacher
     */
    
    private CardLayout clayout;
    public EnrollCourse(JPanel container) {
        initComponents();     
        this.container = container;
        SqliteController.test();
        clayout = (CardLayout) container.getLayout();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        btnEnroll = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtInstructor = new javax.swing.JTextField();
        txtLocation = new javax.swing.JTextField();
        txtSdate = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtEdate = new javax.swing.JTextField();
        txtCoursename = new javax.swing.JTextField();
        txtSubject = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtStime = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtetime = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtwod = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(820, 520));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBack.setBackground(new java.awt.Color(255, 255, 255));
        btnBack.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 360, 90, -1));

        btnEnroll.setBackground(new java.awt.Color(255, 255, 255));
        btnEnroll.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnEnroll.setText("Create");
        btnEnroll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnrollActionPerformed(evt);
            }
        });
        add(btnEnroll, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 360, 110, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setText("Course Name");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, -1, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel6.setText("Instructor");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 270, -1, -1));

        txtInstructor.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtInstructor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtInstructorActionPerformed(evt);
            }
        });
        add(txtInstructor, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 270, 100, -1));

        txtLocation.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtLocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLocationActionPerformed(evt);
            }
        });
        add(txtLocation, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 230, 100, -1));

        txtSdate.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtSdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSdateActionPerformed(evt);
            }
        });
        add(txtSdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 140, 100, -1));

        jLabel7.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel7.setText("Create New Course");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 30, -1, -1));

        jLabel8.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel8.setText("Location");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 230, -1, -1));

        jLabel9.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel9.setText("Subject");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 270, 50, -1));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setText("Start Date");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setText("End Date");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, -1, 20));

        txtEdate.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtEdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEdateActionPerformed(evt);
            }
        });
        add(txtEdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 170, 100, -1));

        txtCoursename.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtCoursename.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCoursenameActionPerformed(evt);
            }
        });
        add(txtCoursename, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 100, 100, -1));

        txtSubject.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtSubject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSubjectActionPerformed(evt);
            }
        });
        add(txtSubject, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 270, 100, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setText("Start Time");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 140, -1, -1));

        txtStime.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtStime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStimeActionPerformed(evt);
            }
        });
        add(txtStime, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 140, 100, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5.setText("End Time");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 170, -1, -1));

        txtetime.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtetime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtetimeActionPerformed(evt);
            }
        });
        add(txtetime, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 170, 100, -1));

        jLabel10.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel10.setText("Week of Day");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, -1, -1));

        txtwod.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtwod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtwodActionPerformed(evt);
            }
        });
        add(txtwod, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 230, 100, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        ((ManageCourse)this.container.getComponent(3)).setTable(SqliteController.getAllTeacher());
        clayout.show(container, "courseManage");
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnEnrollActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnrollActionPerformed
        if(txtCoursename.getText().equals("")||txtSdate.getText().equals("")||txtEdate.getText().equals("")||txtwod.getText().equals("")
                ||txtStime.getText().equals("")||txtetime.getText().equals("")||txtLocation.getText().equals("")||txtSubject.getText().equals("")||txtInstructor.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Please fill out all text fields ^ ^");
        }else{
            StringBuilder sb=new StringBuilder();
            sb.append(CourseController.clist.size()+1).append(",")
                .append(txtCoursename.getText()).append(",")
                .append(txtSdate.getText()).append(",")
                .append(txtEdate.getText()).append(",")
                .append(txtwod.getText()).append(",")
                .append(txtStime.getText()).append(",")
                .append(txtetime.getText()).append(",")
                .append(txtLocation.getText()).append(",")
                .append(txtSubject.getText()).append(",")
                .append(txtInstructor.getText()).append(",");
            CourseController cc=new CourseController(container);
            //int i=cc.addnewCourse(sb.toString());
            int i=SqliteController.insertCourseTablewithstring(sb.toString());
            if(i==0){
                JOptionPane.showMessageDialog(null, "fialed to insert new course");
            }else{
                txtCoursename.setText("");
                txtSdate.setText("");
                txtEdate.setText("");
                txtwod.setText("");
                txtStime.setText("");
                txtetime.setText("");
                txtLocation.setText("");
                txtSubject.setText("");
                txtInstructor.setText("");
                JOptionPane.showMessageDialog(null, "insert new course successfuly!");
                    cc.showCourseTabelfromDB();
                clayout.show(container, "courseManage");
            }
        }
    }//GEN-LAST:event_btnEnrollActionPerformed

    private void txtInstructorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtInstructorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtInstructorActionPerformed

    private void txtLocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLocationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLocationActionPerformed

    private void txtSdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSdateActionPerformed

    private void txtEdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEdateActionPerformed

    private void txtCoursenameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCoursenameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCoursenameActionPerformed

    private void txtSubjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSubjectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSubjectActionPerformed

    private void txtStimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStimeActionPerformed

    private void txtetimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtetimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtetimeActionPerformed

    private void txtwodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtwodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtwodActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnEnroll;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtCoursename;
    private javax.swing.JTextField txtEdate;
    private javax.swing.JTextField txtInstructor;
    private javax.swing.JTextField txtLocation;
    private javax.swing.JTextField txtSdate;
    private javax.swing.JTextField txtStime;
    private javax.swing.JTextField txtSubject;
    private javax.swing.JTextField txtetime;
    private javax.swing.JTextField txtwod;
    // End of variables declaration//GEN-END:variables
}
