/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package userInterface.Course;

import Controller.CourseController;
import Controller.SqliteController;
import java.awt.CardLayout;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 83715
 */
public class ManageCourse extends javax.swing.JPanel {

    JPanel container;
    
    /**
     * Creates new form manageTeacher
     */
    private CardLayout clayout;
    static int selectedCourseId =1;
    static String selectedCourse;
    public ManageCourse(JPanel container) {        
        initComponents();     
        this.container = container;
        SqliteController.test();
        clayout = (CardLayout) container.getLayout();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        CourseTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnDelete = new javax.swing.JButton();
        tbnView = new javax.swing.JButton();
        tbnEnrollCour = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(820, 520));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CourseTable.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        CourseTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "StarttoEndDate", "Time", "Loaction", "Subejct", "Instructor"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(CourseTable);
        if (CourseTable.getColumnModel().getColumnCount() > 0) {
            CourseTable.getColumnModel().getColumn(0).setMaxWidth(25);
            CourseTable.getColumnModel().getColumn(2).setMinWidth(165);
            CourseTable.getColumnModel().getColumn(2).setPreferredWidth(165);
            CourseTable.getColumnModel().getColumn(2).setMaxWidth(165);
            CourseTable.getColumnModel().getColumn(4).setMinWidth(155);
            CourseTable.getColumnModel().getColumn(4).setPreferredWidth(155);
            CourseTable.getColumnModel().getColumn(4).setMaxWidth(155);
            CourseTable.getColumnModel().getColumn(6).setMaxWidth(150);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 1120, 190));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel1.setText("Manage Course");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 30, -1, -1));

        btnDelete.setBackground(new java.awt.Color(255, 255, 255));
        btnDelete.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 360, 80, -1));

        tbnView.setBackground(new java.awt.Color(255, 255, 255));
        tbnView.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tbnView.setText("View Detail");
        tbnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbnViewActionPerformed(evt);
            }
        });
        add(tbnView, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 360, 110, -1));

        tbnEnrollCour.setBackground(new java.awt.Color(255, 255, 255));
        tbnEnrollCour.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tbnEnrollCour.setText("Create Course");
        tbnEnrollCour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbnEnrollCourActionPerformed(evt);
            }
        });
        add(tbnEnrollCour, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 360, 130, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        if(!CourseTable.getSelectionModel().isSelectionEmpty()){
            int row=CourseTable.getSelectedRow();
            Object o=CourseTable.getModel().getValueAt(row, 0);
            if(o !=null){
                int cid=Integer.parseInt(o.toString().trim());
                CourseController cc=new CourseController(container);
                cc.removeCourse(cid);
            }else{
                JOptionPane.showMessageDialog(null, "no course in this table, can not delete.");
            }
        }else{
            JOptionPane.showMessageDialog(null, "Please select one course to delete ^ ^");
        }
        
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void tbnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbnViewActionPerformed
        CourseController cc=new CourseController(container);
        int row=0;
        if(!CourseTable.getSelectionModel().isSelectionEmpty()){
            row=CourseTable.getSelectedRow();    
        }
            Object o=CourseTable.getModel().getValueAt(row, 0);
            if(o !=null){
                selectedCourseId=Integer.parseInt(o.toString());
                selectedCourse=CourseTable.getModel().getValueAt(row, 0).toString();
                    cc.viewCourseEnrollDetailfromDB(selectedCourseId);
                
                clayout.show(container, "viewCourseJPanel");
            }else{
                JOptionPane.showMessageDialog(null, "no course in this table, can not view detail.");
            }
        
        
    }//GEN-LAST:event_tbnViewActionPerformed

    private void tbnEnrollCourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbnEnrollCourActionPerformed
        // TODO add your handling code here:
        //((EnrollCourse)this.container.getComponent(15)).setTable(SqliteController.getAllTeacher());
        clayout.show(container, "enrollCourseJPanel");
    }//GEN-LAST:event_tbnEnrollCourActionPerformed

    //import value from database
    public void setTable(List<Object[]> ol){
        DefaultTableModel tableModel=(DefaultTableModel) CourseTable.getModel();
        if (tableModel.getRowCount() > 0) {
                    for (int i = tableModel.getRowCount() - 1; i > -1; i--) {
                        tableModel.removeRow(i);
                    }
                }
        //tableModel.setColumnIdentifiers(new Object[]{"ID", "Name", "StarttoEndDate","Time", "Location","Subject", "Instructor"}); 
        ol.forEach((e)-> {tableModel.insertRow(ol.indexOf(e),e);});
       CourseTable.setModel(tableModel);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable CourseTable;
    private javax.swing.JButton btnDelete;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton tbnEnrollCour;
    private javax.swing.JButton tbnView;
    // End of variables declaration//GEN-END:variables
}
