/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package userInterface;


import Controller.CourseController;
import Controller.MainController;
import Controller.SqliteController;
import java.awt.CardLayout;
import java.awt.event.ActionListener;
import medical.immunization.VaccineCSVGenerator;
import userInterface.Course.EnrollCourse;
import userInterface.Course.ManageCourse;
import userInterface.Course.ViewCourse;
import userInterface.Immunization.ManageStudentImmunization;
import userInterface.Student.CourseRegistration;
//import userInterface.Student.AddRecord;
import userInterface.Student.EnrollStudent;
import userInterface.Student.ManageStudent;
import userInterface.Student.ViewStudent;
//import userInterface.Student.ViewStudentImmu;
import userInterface.Teacher.EnrollTeacher;
import userInterface.Teacher.ManageTeacher;
import userInterface.Teacher.StudentList;
import userInterface.Teacher.ViewTeacher;

/**
 *
 * @author 83715
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public CardLayout clayout;

    public MainFrame() {
        SqliteController.test();
        initComponents();
        
        clayout=(CardLayout)container.getLayout();
        //add jpanel to container
        synchronized(this){
        ManageTeacher mtp = new ManageTeacher(container);
        ManageStudent msp = new ManageStudent(container);
        ManageStudentImmunization msi = new ManageStudentImmunization(container);
        ManageCourse mcp = new ManageCourse(container);
        ViewCourse vcp = new ViewCourse(container);
        EnrollStudent esp = new EnrollStudent(container);
        EnrollTeacher etp = new EnrollTeacher(container);
        EnrollCourse ecp = new EnrollCourse(container);
        CourseRegistration cr = new CourseRegistration(container);//14->9
        //AssignStudent asp = new AssignStudent(container);
        ViewTeacher vtp = new ViewTeacher(container);
        StudentList sl = new StudentList(container);
        ViewStudent vs = new ViewStudent(container);
        //ViewStudentImmu vsip = new ViewStudentImmu(container);
        
        String name="";
                        
        container.add("teacherManage", mtp);//1
        container.add("studentManage", msp);//2
        container.add("courseManage", mcp);//3
        container.add("viewCourseJPanel",vcp);//4
        container.add("manageStudentImmunizationJPanel",msi);//5
        container.add("enrollStudentJPanel",esp);//6
        container.add("enrollTeacherJPanel",etp);//7
        container.add("enrollCourseJPanel",ecp);//8
        container.add("CourseRegistration", cr);//14->9
        //container.add("assignStudentJPanel",asp);//9
        container.add("viewTeacherJPanel", vtp);//10
        container.add("StudentList", sl);//11
        container.add("ViewStudent", vs);//12
        //container.add("viewStudentRecordJPanel", vsip);//13
        
        }
        /*
        for(Component c:container.getComponents()){
            System.out.println(c.getClass());
        }
        */
        MainController mc=new MainController(this,container);
        
        this.teacherShow(e-> clayout.show(container, "teacherManage"));
         //******************************
         //initialize immunization requirements
         //******************************
         //generate immunization tables
         SqliteController.createVaccineRecordTable();

         VaccineCSVGenerator csv = new VaccineCSVGenerator();
         csv.generateRuleFromSample();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        container = new javax.swing.JPanel();
        rightPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        logoPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        workPanel = new javax.swing.JPanel();
        immunization = new javax.swing.JButton();
        teacher = new javax.swing.JButton();
        student = new javax.swing.JButton();
        course = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        container.setBackground(new java.awt.Color(249, 253, 255));
        container.setLayout(new java.awt.CardLayout());

        rightPanel.setBackground(new java.awt.Color(249, 253, 255));
        rightPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Cooper Black", 0, 48)); // NOI18N
        jLabel1.setText("Information Management System");
        rightPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, -1, -1));

        jLabel3.setFont(new java.awt.Font("Cooper Black", 0, 48)); // NOI18N
        jLabel3.setText("Welcome to Northeasten");
        rightPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 170, -1, -1));

        container.add(rightPanel, "card2");

        getContentPane().add(container, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 1140, 570));

        logoPanel.setBackground(new java.awt.Color(229, 242, 255));
        logoPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userInterface/images.jpeg"))); // NOI18N
        logoPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 0, -1, -1));

        getContentPane().add(logoPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 1140, 90));

        workPanel.setBackground(new java.awt.Color(153, 204, 255));
        workPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        immunization.setBackground(new java.awt.Color(255, 255, 255));
        immunization.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        immunization.setText("Immunization");
        immunization.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                immunizationActionPerformed(evt);
            }
        });
        workPanel.add(immunization, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 110, -1));

        teacher.setBackground(new java.awt.Color(255, 255, 255));
        teacher.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        teacher.setText("Teacher");
        teacher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teacherActionPerformed(evt);
            }
        });
        workPanel.add(teacher, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 110, -1));

        student.setBackground(new java.awt.Color(255, 255, 255));
        student.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        student.setText("Student");
        student.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentActionPerformed(evt);
            }
        });
        workPanel.add(student, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 110, -1));

        course.setBackground(new java.awt.Color(255, 255, 255));
        course.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        course.setText("Course");
        course.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                courseActionPerformed(evt);
            }
        });
        workPanel.add(course, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 110, -1));

        getContentPane().add(workPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 660));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void immunizationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_immunizationActionPerformed
//        ((ViewStudentImmunization_old)this.container.getComponent(3)).setTableUpcoming(SqliteController.getAllTeacher());
//        //container layout show() display panel with name
//        clayout.show(container, "immunizationManage");
        
        ((ManageStudentImmunization)this.container.getComponent(5)).setTable(SqliteController.getAllStudents());
        clayout.show(container, "manageStudentImmunizationJPanel");
        
    }//GEN-LAST:event_immunizationActionPerformed
    public void teacherShow(ActionListener actionListener) {
        teacher.addActionListener(actionListener);
    }
    private void studentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentActionPerformed
        ((ManageStudent)this.container.getComponent(2)).refreshTable();
        clayout.show(container, "studentManage");
        //container.removeAll();
        //container.add(mtp);
        //pack();
        /*
        rightPanel.removeAll();
        rightPanel.add("ManageStudentJPanel",mtp);
        CardLayout layout = (CardLayout) rightPanel.getLayout();
        layout.last(rightPanel);
        */
    }//GEN-LAST:event_studentActionPerformed

    private void courseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_courseActionPerformed
        CourseController cc=new CourseController(container);
        cc.showCourseTabelfromDB();
        clayout.show(container, "courseManage");

    }//GEN-LAST:event_courseActionPerformed

    private void teacherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teacherActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_teacherActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel container;
    private javax.swing.JButton course;
    private javax.swing.JButton immunization;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel logoPanel;
    private javax.swing.JPanel rightPanel;
    private javax.swing.JButton student;
    private javax.swing.JButton teacher;
    private javax.swing.JPanel workPanel;
    // End of variables declaration//GEN-END:variables
}
