/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package userInterface.Student;


import Controller.SqliteController;
import Model.Organization.Subject;
import Model.Person.Student;
import userInterface.Teacher.*;

import java.awt.CardLayout;
import java.awt.Component;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 * @author 83715
 */
public class EnrollStudent extends javax.swing.JPanel {

    JPanel rightPanel;

    /**
     * Creates new form manageTeacher
     */
    public EnrollStudent(JPanel rp) {
        initComponents();
        rightPanel = rp;
        cmbSubject.setModel(new javax.swing.DefaultComboBoxModel<>(SqliteController.getAllSubjectModel().toArray()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        btnEnroll = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtAge = new javax.swing.JTextField();
        txtNUID = new javax.swing.JTextField();
        txtFname = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtMname = new javax.swing.JTextField();
        txtFaname = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtPhone = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        cmbSubject = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        cmbGender = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        txtLname1 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtEntryYear = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBack.setBackground(new java.awt.Color(255, 255, 255));
        btnBack.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 90, -1));

        btnEnroll.setBackground(new java.awt.Color(255, 255, 255));
        btnEnroll.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnEnroll.setText("Enroll");
        btnEnroll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnrollActionPerformed(evt);
            }
        });
        add(btnEnroll, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 350, 110, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setText("First Name");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5.setText("Age");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, -1, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel6.setText("Subject");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, -1, -1));

        txtAge.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAgeActionPerformed(evt);
            }
        });
        add(txtAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 290, 100, -1));

        txtNUID.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtNUID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNUIDActionPerformed(evt);
            }
        });
        add(txtNUID, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 100, -1));

        txtFname.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtFname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFnameActionPerformed(evt);
            }
        });
        add(txtFname, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 100, -1));

        jLabel7.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel7.setText("Enroll New Student");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, -1, -1));

        jLabel8.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel8.setText("NUID");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel2.setText("Students' Info");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setText("Father Name");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 100, -1, -1));

        txtMname.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtMname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMnameActionPerformed(evt);
            }
        });
        add(txtMname, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 140, 100, -1));

        txtFaname.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtFaname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFanameActionPerformed(evt);
            }
        });
        add(txtFaname, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 100, 100, -1));

        jLabel9.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel9.setText("Mother Name");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 140, -1, -1));

        jLabel10.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel10.setText("Parents' Info");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 60, -1, -1));

        txtPhone.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPhoneActionPerformed(evt);
            }
        });
        add(txtPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 180, 100, -1));

        jLabel12.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel12.setText("Phone");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 180, -1, -1));

        jLabel13.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel13.setText("Address");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 220, -1, -1));

        txtAddress.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAddressActionPerformed(evt);
            }
        });
        add(txtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 220, 260, -1));

        cmbSubject.setModel(new javax.swing.DefaultComboBoxModel<>(new Object[]{}));
        cmbSubject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbSubjectActionPerformed(evt);
            }
        });
        add(cmbSubject, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, 100, -1));
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, -1, -1));

        jLabel11.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel11.setText("Gender");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, -1, -1));

        cmbGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Male", "Female"}));
        add(cmbGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, 100, -1));

        jLabel14.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel14.setText("Last Name");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, -1));

        txtLname1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtLname1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLname1ActionPerformed(evt);
            }
        });
        add(txtLname1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 100, -1));

        jLabel15.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel15.setText("Entry Year");
        add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, -1, -1));

        txtEntryYear.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtEntryYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEntryYearActionPerformed(evt);
            }
        });
        add(txtEntryYear, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 320, 100, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        ManageStudent etp = new ManageStudent(rightPanel);
        rightPanel.remove(this);
        rightPanel.add(etp);
        CardLayout layout = (CardLayout) rightPanel.getLayout();
        layout.previous(rightPanel);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnEnrollActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnrollActionPerformed
        // TODO add your handling code here:
        if (txtFname.getText() == null || txtFname.getText().isEmpty()
                || txtNUID.getText() == null || txtNUID.getText().isEmpty()
                || cmbGender.getSelectedItem().toString() == null || cmbGender.getSelectedItem().toString().isEmpty()
                || cmbSubject.getSelectedItem() == null
                || txtAge.getText() == null || txtAge.getText().isEmpty()
                || txtFaname.getText() == null || txtFaname.getText().isEmpty()
                || txtMname.getText() == null || txtMname.getText().isEmpty()
                || txtPhone.getText() == null || txtPhone.getText().isEmpty()
                || txtAddress.getText() == null || txtAddress.getText().isEmpty()
                || txtEntryYear.getText() == null || txtEntryYear.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Sorry, the text box cannot be empty.");
            return;
        }

        int subjectId = cmbSubject.getSelectedItem() == null ? 0 : ((Subject) cmbSubject.getSelectedItem()).getSubjectID();
        int id = SqliteController.insertStudent(txtFaname.getText(), txtMname.getText(), txtPhone.getText(),
                txtAddress.getText(), txtEntryYear.getText(), subjectId, txtFname.getText(), txtLname1.getText(),
                Integer.parseInt(txtAge.getText()), cmbGender.getSelectedItem().toString());

        if (id > 0) {
            JOptionPane.showMessageDialog(this, "Student's enrollment is successful!");
        } else {
            JOptionPane.showMessageDialog(this, "Student's enrollment is fail!");
        }


    }//GEN-LAST:event_btnEnrollActionPerformed

    private void txtAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAgeActionPerformed

    private void txtNUIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNUIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNUIDActionPerformed

    private void txtFnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFnameActionPerformed

    private void txtMnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMnameActionPerformed

    private void txtFanameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFanameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFanameActionPerformed

    private void txtPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPhoneActionPerformed

    private void txtAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAddressActionPerformed

    private void cmbSubjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbSubjectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbSubjectActionPerformed

    private void txtLname1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLname1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLname1ActionPerformed

    private void txtEntryYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEntryYearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEntryYearActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnEnroll;
    private javax.swing.JComboBox<String> cmbGender;
    private javax.swing.JComboBox<Object> cmbSubject;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtEntryYear;
    private javax.swing.JTextField txtFaname;
    private javax.swing.JTextField txtFname;
    private javax.swing.JTextField txtLname1;
    private javax.swing.JTextField txtMname;
    private javax.swing.JTextField txtNUID;
    private javax.swing.JTextField txtPhone;
    // End of variables declaration//GEN-END:variables
}
