/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package userInterface.Student;

import Controller.SqliteController;
import Model.Person.Student;

import userInterface.Teacher.*;

import java.awt.CardLayout;
import java.util.List;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

/**
 * @author 83715
 */
public class ManageStudent extends javax.swing.JPanel {

    JPanel rightPanel;

    /**
     * Creates new form manageTeacher
     */
    public ManageStudent(JPanel rp) {
        initComponents();
        rightPanel = rp;

        refreshTable();
    }


    public void refreshTable() {
        DefaultTableModel model = (DefaultTableModel) StudentTable.getModel();
        int size = model.getRowCount();
        for (int i = 0; i < size; i++) {
            model.removeRow(0);
        }
        for (Student student : SqliteController.getAllStudentModel()) {
            Object[] row = new Object[7];
            row[0] = student.getId();
            row[1] = student.getfName();
            row[2] = student.getlName();
            row[3] = student.getAge();
            row[4] = student.getGender();
            row[5] = student.getSubject() == null ? "" : student.getSubject().getSubjectName();
            row[6] = student.getEntryYear();
            model.addRow(row);
        }


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        StudentTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnDelete = new javax.swing.JButton();
        tbnEnrollStudent = new javax.swing.JButton();
        tbnView1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(650, 400));
        setPreferredSize(new java.awt.Dimension(650, 400));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        StudentTable.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        StudentTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "NUID", "FirstName", "LastName", "Age", "Gender", "Subject", "EntryYear"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, false, false, false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(StudentTable);
        if (StudentTable.getColumnModel().getColumnCount() > 0) {
            StudentTable.getColumnModel().getColumn(0).setMaxWidth(150);
            StudentTable.getColumnModel().getColumn(3).setMaxWidth(50);
            StudentTable.getColumnModel().getColumn(4).setMaxWidth(100);
            StudentTable.getColumnModel().getColumn(6).setMaxWidth(100);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 780, 190));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel1.setText("Manage Student ");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 50, -1, -1));

        btnDelete.setBackground(new java.awt.Color(255, 255, 255));
        btnDelete.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 80, -1));

        tbnEnrollStudent.setBackground(new java.awt.Color(255, 255, 255));
        tbnEnrollStudent.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tbnEnrollStudent.setText("Enroll Student");
        tbnEnrollStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbnEnrollStudentActionPerformed(evt);
            }
        });
        add(tbnEnrollStudent, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 400, 120, -1));

        tbnView1.setBackground(new java.awt.Color(255, 255, 255));
        tbnView1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tbnView1.setText("View Detail");
        tbnView1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbnView1ActionPerformed(evt);
            }
        });
        add(tbnView1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 400, 110, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int row = StudentTable.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row!!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        String id = (String) StudentTable.getValueAt(row, 0);
        boolean result = SqliteController.deleteStudent(Integer.parseInt(id));
        if (result) {
            JOptionPane.showMessageDialog(this, "Student's delete is successful!");
        } else {
            JOptionPane.showMessageDialog(this, "Student's delete is fail!");
        }
        refreshTable();
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void tbnEnrollStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbnEnrollStudentActionPerformed
        // TODO add your handling code here:
        CardLayout layout = (CardLayout) rightPanel.getLayout();
        layout.show(rightPanel,"enrollStudentJPanel");
    }//GEN-LAST:event_tbnEnrollStudentActionPerformed

    private void tbnView1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbnView1ActionPerformed
        // TODO add your handling code here:
        int row = StudentTable.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row!!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }else{
        int id = Integer.parseInt(StudentTable.getValueAt(row, 0).toString());
        ViewStudent vs=(ViewStudent)this.rightPanel.getComponent(12);
        vs.setStudnetID(id);
        CardLayout layout = (CardLayout) rightPanel.getLayout();
        layout.show(rightPanel,"ViewStudent");
        }
    }//GEN-LAST:event_tbnView1ActionPerformed

    //import value from database
   /* public void setTable(List<Object[]> ol) {
        DefaultTableModel tableModel = (DefaultTableModel) StudentTable.getModel();
        tableModel.setColumnIdentifiers(new Object[]{"ID", "FirstName", "LastName", "Age", "Subject"});
        ol.forEach((e) -> {
            tableModel.addRow(e);
        });
        StudentTable.setModel(tableModel);
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable StudentTable;
    private javax.swing.JButton btnDelete;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton tbnEnrollStudent;
    private javax.swing.JButton tbnView1;
    // End of variables declaration//GEN-END:variables
}
