/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.Teacher;

import Controller.SqliteController;
import userInterface.Student.ViewStudent;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.util.List;

/**
 * @author Lynn Wei
 */
public class StudentList extends javax.swing.JPanel {

    /**
     * Creates new form StudentList
     */
    JPanel rightPanel;
    int courseId;
    static int selectedStudentid;

    public StudentList(JPanel rp) {
        initComponents();
        rightPanel = rp;
        this.courseId = ViewTeacher.selectedcid;
        
    }
    public void setCourseID(int id){
        this.courseId = id;
        populateData();
    }
    private void populateData(){
        List<Object[]> studentList = SqliteController.getStudentByCourseId(courseId);
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        int size = model.getRowCount();
        for (int i = 0; i < size; i++) {
            model.removeRow(0);
        }
        studentList.forEach((e)-> {model.insertRow(studentList.indexOf(e),e);});
        jTable1.setModel(model);
        /*
        for (Object[] student : studentList) {
            Object[] row = new Object[6];
            row[0] = student.getId();
            row[1] = student.getName();
            row[2] = student.getGender();
            row[3] = student.getAge();
            row[4] = student.getSubject()== null ?"":student.getSubject().getSubjectName();
            row[5] = student.getEntryYear();
            model.addRow(row);
        }
        */
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        btnStudentDetail = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "NUID", "Name", "Gender", "Age", "Subject", "Entry Year"
            }
        ));
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setMaxWidth(80);
            jTable1.getColumnModel().getColumn(3).setMaxWidth(50);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 99, 770, 230));

        jLabel7.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel7.setText("Student List");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 30, -1, -1));

        btnBack.setBackground(new java.awt.Color(255, 255, 255));
        btnBack.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 34, 90, -1));

        btnStudentDetail.setBackground(new java.awt.Color(255, 255, 255));
        btnStudentDetail.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnStudentDetail.setText(" Student Details");
        btnStudentDetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStudentDetailActionPerformed(evt);
            }
        });
        add(btnStudentDetail, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 360, 150, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnStudentDetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStudentDetailActionPerformed
        // TODO add your handling code here:
        int row = jTable1.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row!!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        selectedStudentid = Integer.parseInt(jTable1.getValueAt(row, 0).toString());
        ViewStudent vs=(ViewStudent)this.rightPanel.getComponent(12);
        vs.setStudnetID(selectedStudentid);
        CardLayout layout = (CardLayout) rightPanel.getLayout();
        layout.show(rightPanel,"ViewStudent");
    }//GEN-LAST:event_btnStudentDetailActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnStudentDetail;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
